services:
  - type: web
    name: plannerme-teacher-super-aid
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run sidekick.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
